export const TABLE_RECEIVE_USERS_DATA = "TABLE_RECEIVE_USERS_DATA";
export const TABLE_SET_IS_FETCHING = "TABLE_SET_IS_FETCHING";
export const TABLE_ADD_NEW_RECORD = "TABLE_ADD_NEW_RECORD";
export const TABLE_SET_EDITING_ID = "TABLE_SET_EDITING_ID";
export const TABLE_EDIT_USER = "TABLE_EDIT_USER";
export const TABLE_DELETE_USER = "TABLE_DELETE_USER";
